package org.example.check;

import eu.cqse.check.framework.core.Check;
import eu.cqse.check.framework.core.CheckImplementationBase;
import eu.cqse.check.framework.core.EFindingEnablement;
import eu.cqse.check.framework.scanner.ELanguage;
import org.conqat.lib.simulink.model.SimulinkBlock;
import org.conqat.lib.simulink.model.SimulinkModel;
import org.conqat.lib.simulink.util.SimulinkUtils;

/**
 * Sample check on simulink model, for testing purposes.
 */
@Check(name = "Simulink Sample Check", groupName = "Sample Check Group", defaultEnablement = EFindingEnablement.YELLOW, languages = ELanguage.SIMULINK)
public class SimulinkSampleCheck extends CheckImplementationBase {

	/** {@inheritDoc} */
	@Override
	public void execute() {
		/*
		 * This is an example check that demonstrates how to write custom checks for simulink models. The
		 * check generates a finding for each block that has inputs or outputs. I know that these findings
		 * are not useful for model-quality assessment. It is just meant as demonstration and it will
		 * generate findings on almost every model.
		 */

		SimulinkModel model = context.getSimulinkContext().getSimulinkModelForModelFile().orElse(null);
		if (model == null) {
			return;
		}
		for (SimulinkBlock block : SimulinkUtils.listBlocksDepthFirst(model,
				// ignore blocks that are not user visible (e.g., autogenerated simulink blocks
				// below Stateflow Chart blocks)
				false,
				// ignore blocks that are commented out or are below commented-out blocks.
				false)) {
			int numInLines = block.getInLines().size();
			if (numInLines > 0) {
				buildFinding("block has " + numInLines + " input lines. I don't allow any!",
						buildLocation().forSimulinkBlock(block)).addFindingProperties(null).createAndStore();
			}
			int numOutLines = block.getOutLines().size();
			if (numOutLines > 0) {
				buildFinding("block has " + numOutLines + " output lines. I don't allow any!",
						buildLocation().forSimulinkBlock(block)).addFindingProperties(null).createAndStore();
			}
		}
	}
}
